### ISSUE TITLE
Failed on both 0.4 and master

### ISSUE THREAD

**Issue by sfchen** [BioJulia/Libz.jl#29]
Mac OSX, both failing

**Comment by bicycle1885** [comment]
Can you give me more details? Version, reproducible code, etc. I cannot do anything without it. The current release version (v0.1.1) passed tests on Travis CI (https://travis-ci.org/BioJulia/Libz.jl/builds/129039284).

**Comment by sfchen** [comment]
0.4.2 is failing

julia> Pkg.test("Libz")
INFO: Computing test dependencies for Libz...
INFO: Installing FactCheck v0.4.2
INFO: Testing Libz
Source
  Error :: (line:505)
    Expression: test_round_trip(UInt8[]) --> true
    MethodError: `readbytes!` has no method matching readbytes!(::Libz.Source{:inflate,BufferedStreams.BufferedInputStream{Libz.Source{:deflate,BufferedStreams.BufferedInputStream{BufferedStreams.EmptyStream}}}}, ::Array{UInt8,1}, ::Int64, ::Int64)
    you may have intended to import Base.readbytes!
    Closest candidates are:
      readbytes!(::BufferedStreams.BufferedInputStream{T}, ::AbstractArray{UInt8,N}, ::Int64, ::Int64)
      readbytes!(::IOStream, ::AbstractArray{UInt8,N}, ::Int64, ::Int64)
      readbytes!(::IO, ::AbstractArray{UInt8,N}, ::Int64, ::Int64)
      ...
     in fillbuffer! at /Users/shifu/.julia/v0.4/BufferedStreams/src/bufferedinputstream.jl:71
     in readbytes! at io.jl:240
     in readbytes at io.jl:258
     in readbytes at io.jl:257
     in test_round_trip at /Users/shifu/.julia/v0.4/Libz/test/runtests.jl:8
     in anonymous at /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in do_fact at /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:333
     [inlined code] from /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in anonymous at /Users/shifu/.julia/v0.4/Libz/test/runtests.jl:7
     in facts at /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:448
     in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in process_options at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in _start at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
  Error :: (line:505)
    Expression: test_round_trip(rand(UInt8,1)) --> true
    MethodError: `readbytes!` has no method matching readbytes!(::Libz.Source{:inflate,BufferedStreams.BufferedInputStream{Libz.Source{:deflate,BufferedStreams.BufferedInputStream{BufferedStreams.EmptyStream}}}}, ::Array{UInt8,1}, ::Int64, ::Int64)
    you may have intended to import Base.readbytes!
    Closest candidates are:
      readbytes!(::BufferedStreams.BufferedInputStream{T}, ::AbstractArray{UInt8,N}, ::Int64, ::Int64)
      readbytes!(::IOStream, ::AbstractArray{UInt8,N}, ::Int64, ::Int64)
      readbytes!(::IO, ::AbstractArray{UInt8,N}, ::Int64, ::Int64)
      ...
     in fillbuffer! at /Users/shifu/.julia/v0.4/BufferedStreams/src/bufferedinputstream.jl:71
     in readbytes! at io.jl:240
     in readbytes at io.jl:258
     in readbytes at io.jl:257
     in test_round_trip at /Users/shifu/.julia/v0.4/Libz/test/runtests.jl:8
     in anonymous at /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in do_fact at /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:333
     [inlined code] from /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in anonymous at /Users/shifu/.julia/v0.4/Libz/test/runtests.jl:7
     in facts at /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:448
     in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in process_options at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in _start at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
  Error :: (line:505)
    Expression: test_round_trip(rand(UInt8,1000000)) --> true
    MethodError: `readbytes!` has no method matching readbytes!(::Libz.Source{:inflate,BufferedStreams.BufferedInputStream{Libz.Source{:deflate,BufferedStreams.BufferedInputStream{BufferedStreams.EmptyStream}}}}, ::Array{UInt8,1}, ::Int64, ::Int64)
    you may have intended to import Base.readbytes!
    Closest candidates are:
      readbytes!(::BufferedStreams.BufferedInputStream{T}, ::AbstractArray{UInt8,N}, ::Int64, ::Int64)
      readbytes!(::IOStream, ::AbstractArray{UInt8,N}, ::Int64, ::Int64)
      readbytes!(::IO, ::AbstractArray{UInt8,N}, ::Int64, ::Int64)
      ...
     in fillbuffer! at /Users/shifu/.julia/v0.4/BufferedStreams/src/bufferedinputstream.jl:71
     in readbytes! at io.jl:240
     in readbytes at io.jl:258
     in readbytes at io.jl:257
     in test_round_trip at /Users/shifu/.julia/v0.4/Libz/test/runtests.jl:8
     in anonymous at /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in do_fact at /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:333
     [inlined code] from /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:271
     in anonymous at /Users/shifu/.julia/v0.4/Libz/test/runtests.jl:7
     in facts at /Users/shifu/.julia/v0.4/FactCheck/src/FactCheck.jl:448
     in include at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in include_from_node1 at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in process_options at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
     in _start at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
Out of 3 total facts:
  Errored:  3
Sink
  Failure :: (line:505) :: fact was false
    Expression: test_round_trip(rand(UInt8,1)) --> true
      Expected: true
      Occurred: false

**Comment by sfchen** [comment]
`master` is PASSED with some warnings

INFO: Computing test dependencies for Libz...
INFO: Installing BaseTestNext v0.2.1
INFO: Testing Libz
INFO: Recompiling stale cache file /Users/shifu/.julia/lib/v0.5/BufferedStreams.ji for module BufferedStreams.
INFO: Recompiling stale cache file /Users/shifu/.julia/lib/v0.5/Libz.ji for module Libz.
WARNING: `@unix_only` is deprecated, use `@static if is_unix()` instead
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in @unix_only(::Any) at ./deprecated.jl:494
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
while loading /Users/shifu/.julia/v0.5/Libz/src/zlib_h.jl, in expression starting on line 3
WARNING: bytestring(p::Union{Ptr{Int8},Ptr{UInt8}}) is deprecated, use String(p) instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in bytestring(::Ptr{UInt8}) at ./deprecated.jl:50
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:225
 in process_options(::Base.JLOptions) at ./client.jl:243
 in _start() at ./client.jl:322
while loading /Users/shifu/.julia/v0.5/Libz/src/zlib_h.jl, in expression starting on line 8
WARNING: bytestring(p::Union{Ptr{Int8},Ptr{UInt8}}) is deprecated, use String(p) instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in bytestring(::Ptr{UInt8}) at ./deprecated.jl:50
 in zerror(::Libz.ZStream, ::Int32) at /Users/shifu/.julia/v0.5/Libz/src/zlib_h.jl:149
 in process(::Libz.Source{:inflate,BufferedStreams.BufferedInputStream{BufferedStreams.EmptyStream}}, ::Int32) at /Users/shifu/.julia/v0.5/Libz/src/source.jl:182
 in readbytes!(::Libz.Source{:inflate,BufferedStreams.BufferedInputStream{BufferedStreams.EmptyStream}}, ::Array{UInt8,1}, ::Int64, ::Int64) at /Users/shifu/.julia/v0.5/Libz/src/source.jl:142
 in fillbuffer!(::BufferedStreams.BufferedInputStream{Libz.Source{:inflate,BufferedStreams.BufferedInputStream{BufferedStreams.EmptyStream}}}) at /Users/shifu/.julia/v0.5/BufferedStreams/src/bufferedinputstream.jl:72
 in eof at /Users/shifu/.julia/v0.5/BufferedStreams/src/bufferedinputstream.jl:84 [inlined]
 in readbytes!(::BufferedStreams.BufferedInputStream{Libz.Source{:inflate,BufferedStreams.BufferedInputStream{BufferedStreams.EmptyStream}}}, ::Array{UInt8,1}, ::Int64) at ./io.jl:330
 in read(::BufferedStreams.BufferedInputStream{Libz.Source{:inflate,BufferedStreams.BufferedInputStream{BufferedStreams.EmptyStream}}}, ::Int64) at ./io.jl:350
 in macro expansion; at /Users/shifu/.julia/v0.5/Libz/test/runtests.jl:39 [inlined]
 in macro expansion; at ./test.jl:583 [inlined]
 in anonymous at ./<missing>:580
 in include_from_node1(::String) at ./loading.jl:426
 in process_options(::Base.JLOptions) at ./client.jl:266
 in _start() at ./client.jl:322
while loading /Users/shifu/.julia/v0.5/Libz/test/runtests.jl, in expression starting on line 12
Test Summary: | Pass  Total
Source        |   94     94
Test Summary: | Pass  Total
Sink          |   55     55
Test Summary:   | Pass  Total
Inflate/Deflate |    1      1
Test Summary: | Pass  Total
Checksums     |    4      4
Test Summary:           | Pass  Total
Concatenated gzip files |    1      1
Test Summary: | Pass  Total
Error         |    6      6
INFO: Libz tests passed
INFO: Removing BaseTestNext v0.2.1

**Comment by sfchen** [comment]
Sorry, after a manual update of METADA,seems it is working.

My METADATA was broken and blocked any further updating..

Closing this issue

**Comment by bicycle1885** [comment]
😄
