### ISSUE TITLE
needs update for string.data changes

### ISSUE THREAD

**Issue by stevengj** [BioJulia/Libz.jl#40]
After JuliaLang/julia#19449, soon to be merged for Julia 0.6, you will no longer be able to access the raw bytes of a string via `string.data`; instead, do `Vector{UInt8}(string)`.  For example, this affects:

https://github.com/BioJulia/Libz.jl/blob/1838a247a1402b01d9987a729e609b942e7b7120/test/runtests.jl#L114

**Comment by musm** [comment]
closed by https://github.com/BioJulia/Libz.jl/pull/41

**Comment by TransGirlCodes** [comment]
Do you mean #42 and #43 ?

**Comment by musm** [comment]
No those are just for the deprecations
