### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by davidanthoff** [BioJulia/Libz.jl#64]
Could someone please tag a release? It would make things a lot easier for downstream packages that are trying to migrate to 0.7.

**Comment by TransGirlCodes** [comment]
@davidanthoff @GunnarFarneback I've tagged a version v0.4.0 of the most recent depeceation and backwards compatibility PRs.

**Comment by TransGirlCodes** [comment]
If anyone is migrating to 0.7 I would suggest trying to move to CodecZlib.jl whilst doing so.
